fullname = "Andrei Jiroh Halili"
gemini = "gemini.andreijiroh.eu.org"
website = "https://andreijiroh.eu.org"
description = "Open-source maintainer and web dev at Recap Time Squad, sometimes NixOS + Alpine Linux user, #ActuallyAutistic"
email = "ajhalili2006@andreijiroh.eu.org"
matrix = "@ajhalili2006:envs.net"
fediverse = "tilde.zone/@ajhalili2006"
location = "Marilao, Bulacan, Philippines"
